pom.xml, src/main/java/com/cognifide/aemrules/checks/AdministrativeAccessUsageCheck.java, src/main/java/com/cognifide/aemrules/extensions/CheckListRegistrar.java, src/main/resources/rules/AEM-11.md, src/test/files/checks/AdministrativeAccessUsageCheck.java, src/test/java/com/cognifide/aemrules/checks/AdministrativeAccessUsageCheckTest.java
RND-346 - administrative access usage check rule
=> RND-346 - administrative access usage check rule

src/main/java/com/cognifide/aemrules/checks/SynchornizedKeywordUsageCheck.java, src/test/files/checks/SynchornizedKeywordUsageCheck.java
=> #23 fix: issue appears near to synchornized keyword

src/main/java/com/cognifide/aemrules/checks/slice/iterator/IteratingResourcesCheck.java, src/main/java/com/cognifide/aemrules/checks/slice/jcrproperty/GatherAnnotatedVariables.java, src/main/java/com/cognifide/aemrules/checks/slice/jcrproperty/JcrPropertyFieldsInConstructorCheck.java, src/main/java/com/cognifide/aemrules/checks/slice/session/ModelsShouldNotUseSessionCheck.java, src/main/java/com/cognifide/aemrules/extensions/CheckListRegistrar.java, src/main/java/com/cognifide/aemrules/tag/Tags.java, src/test/files/checks/jcrproperty/NoJcrPropertyModel.java, src/test/java/com/cognifide/aemrules/checks/JcrPropertyFieldsInConstructorTest.java
=> #27 add check for @SliceResource annotation before class visiting

README.md, src/main/java/com/cognifide/aemrules/checks/slingmodels/DefaultInjectionStrategyAnnotationCheck.java, src/test/files/checks/slingmodels/DefaultInjectionStrategyAnnotationCheckMultipleAdaptables.java, src/test/java/com/cognifide/aemrules/checks/DefaultInjectionStrategyAnnotationCheckTest.java
ld #46
Added new test case & fixed the bug when Sling Model has multiple adaptables.
=> Fix for multiple adaptables in Sling Model

pom.xml, src/main/java/com/cognifide/aemrules/checks/SessionShouldBeLoggedOut.java, src/main/java/com/cognifide/aemrules/checks/resourceresolver/close/ResourceResolverShouldBeClosed.java
Revert changes in SessionShouldBeLoggedOut.java (Activate.class caused problems with build). Minor style improvments in ResourceResolverShouldBeClosed.java.
=> Revert changes in SessionShouldBeLoggedOut.java

pom.xml
This closes #66 and closes #67
=> Added support for SonarQube 6.4 & Java Plugin 4.10.x

src/main/java/com/cognifide/aemrules/checks/ContentResourceShouldBeNullCheckedCheck.java
=> Issue 65 - refactoring proposal

pom.xml
=> Enable AEM Rules in SonarLint #100

src/main/java/com/cognifide/aemrules/extensions/CheckListRegistrar.java
=> #104 Cannot start SonarQube because of duplicated rule

README.md, src/main/java/com/cognifide/aemrules/htl/checks/AvoidUsingUnsafeDisplayContextCheck.java, src/main/java/com/cognifide/aemrules/htl/checks/PlaceTemplatesInSeparateFilesCheck.java, src/main/java/com/cognifide/aemrules/htl/checks/UseMostRestrictiveHtlContextCheck.java, src/main/java/com/cognifide/aemrules/htl/visitors/HtlStringOptionVisitor.java, src/main/resources/rules/HTL-12.md, src/main/resources/rules/HTL-13.md, src/test/files/checks/htl/AvoidUsingUnsafeDisplayContextCheck.html, src/test/files/checks/htl/HtlAttributesShouldBeAtTheEndCheck.html, src/test/files/checks/htl/NamingAndReusingConditionsCheck.html, src/test/files/checks/htl/UseMostRestrictiveHtlContextCheck.html, src/test/java/com/cognifide/aemrules/htl/checks/AvoidUsingUnsafeDisplayContextCheckTest.java, src/test/java/com/cognifide/aemrules/htl/checks/UseMostRestrictiveHtlContextCheckTest.java
Defined rules:
* **HTL-12** Use the most restrictive HTL context possible.
* **HTL-13** Avoid using 'unsafe' display context.
=> #117 - Security

README.md, src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java, src/main/resources/rules/HTL-14.md, src/test/files/checks/htl/DisplayContextInConditionalCommentsCheck.html, src/test/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheckTest.java
* **HTL-14** - HTL expressions in HTML comments should have defined context.
=> Issue 150 - Conditional Comments

src/main/java/com/cognifide/aemrules/java/checks/resourceresolver/close/ResourceResolverTryWithResourcesCheck.java, src/main/java/com/cognifide/aemrules/java/rules/JavaCheckClasses.java, src/main/resources/rules/AEM-20.md, src/test/files/checks/java/resourceresolver/AutoclosableResourceResolver.java, src/test/java/com/cognifide/aemrules/java/checks/ResourceResolverTryWithResourcesTest.java
=> Issue 81- ResourceResolver should be closed in try-with-resources

src/main/java/com/cognifide/aemrules/htl/HtlFilePredicateProvider.java, src/main/java/com/cognifide/aemrules/htl/checks/DefaultDisplayContextCheck.java, src/main/java/com/cognifide/aemrules/htl/checks/PlaceTemplatesInSeparateFilesCheck.java, src/main/java/com/cognifide/aemrules/htl/checks/UseMostRestrictiveHtlContextCheck.java, src/main/java/com/cognifide/aemrules/htl/rules/HtlCheckClasses.java, src/main/resources/rules/HTL-1.md, src/main/resources/rules/HTL-4.md, src/main/resources/rules/HTL-6.md, src/test/java/com/cognifide/aemrules/htl/HtlProfileTest.java
Issue - #155
* fix **htl-6** key and description
* register new rules definition
* skiping sly data attribute tags for **htl-12**
* fix exceptions on **htl-2**
=> Issue 155 - bugfixes

README.md, src/main/java/com/cognifide/aemrules/htl/checks/ExplicitNamesInLoopsCheck.java, src/main/resources/rules/HTL-3.md, src/test/files/checks/htl/ExplicitNamesInLoopsCheck.html, src/test/java/com/cognifide/aemrules/htl/checks/ExplicitNamesInLoopsCheckTest.java
fixes #115 
First pull request closed: https://github.com/Cognifide/AEM-Rules-for-SonarQube/pull/125
=> Issue 115 - Use Explicit Names in Loops

src/main/java/com/cognifide/aemrules/htl/checks/UseSlyTagsOverRedundantMarkupCheck.java, src/test/files/checks/htl/AvoidExtraSlyTagsCheck.html, src/test/files/checks/htl/UseSlyTagsOverRedundantMarkupCheck.html
* additional condition to avoiding rules overlapping
* extend html samples for unit test for **htl-10** and **htl-11**
=> #111 - bugfix - avoiding rules overlapping

src/main/java/com/cognifide/aemrules/htl/checks/PlaceTemplatesInSeparateFilesCheck.java, src/test/files/checks/htl/PlaceTemplatesInSeparateFilesCheck.html
Fix issues with **htl-2**:
* duplicated violations
* violation created for call statement
=> Issue 112 bugfix

src/main/resources/rules/HTL-12.md
** HTL-12 **
Added table will help developers adjust markup context for HTL expressions.
=> #117 - add description for HTL-12

src/main/java/com/cognifide/aemrules/htl/checks/DisplayContextInConditionalCommentsCheck.java, src/main/java/com/cognifide/aemrules/htl/checks/HtlCommentsCheck.java, src/test/files/checks/htl/HtlCommentsCheck.html
Fixes #109 and a bug from #150.
=> Issue-109 Use HTL comments FIX for multiline comments and exceptions.

src/main/java/com/cognifide/aemrules/htl/checks/AvoidExtraSlyTagsCheck.java, src/test/files/checks/htl/AvoidExtraSlyTagsCheck.html
**htl-11** - fix duplicated violations when htl-11 is not applicable
=> htl-11 - bugfix - fix duplicated violations

src/main/resources/rules/AEM-17.md, src/main/resources/rules/AEM-18.md, src/main/resources/rules/AEM-19.md, src/main/resources/rules/AEM-20.md, src/main/resources/rules/HTL-1.md, src/main/resources/rules/HTL-10.md, src/main/resources/rules/HTL-11.md, src/main/resources/rules/HTL-12.md, src/main/resources/rules/HTL-13.md, src/main/resources/rules/HTL-14.md, src/main/resources/rules/HTL-3.md, src/main/resources/rules/HTL-4.md, src/main/resources/rules/HTL-5.md, src/main/resources/rules/HTL-6.md, src/main/resources/rules/HTL-7.md, src/main/resources/rules/HTL-8.md, src/main/resources/rules/HTL-9.md
* improve **htl-12** description formatting
* fix description issues in HTL rules
=> Issue 169 - description formatting

src/main/java/com/cognifide/aemrules/htl/checks/SlyElementsAreAutomaticallyUnwrappedCheck.java, src/main/java/com/cognifide/aemrules/htl/rules/HtlCheckClasses.java, src/main/resources/rules/HTL-12.md, src/main/resources/rules/HTL-16.md, src/test/files/checks/htl/SlyElementsAreAutomaticallyUnwrappedCheck.html, src/test/java/com/cognifide/aemrules/htl/HtlProfileTest.java, src/test/java/com/cognifide/aemrules/htl/checks/SlyElementsAreAutomaticallyUnwrappedCheckTest.java
* defined **HTL-16** - HTL sly elements are automatically unwrapped
* update description in **HTL-12**
* register **HTL-3**
=> htl - 16 - HTL sly elements are automatically unwrapped

pom.xml
also the repository address for maven central was not working anymore.
=> update the repository URLs to use HTTPs

.github/workflows/test-instalation.yml, pom.xml
=> Issue 228 remove explicit dependency on java plugin
